# Generated by Django 5.0.1 on 2026-01-12 18:01

import django.db.models.deletion
import django.utils.timezone
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('coop', 'Co-op'), ('pvp', 'PvP')], max_length=10)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('mode', models.CharField(choices=[('coop', 'Co-op'), ('pvp', 'PvP')], default='coop', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=10)),
                ('level_number', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=4)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slot', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.multiplayerroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player_slot'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
