# Generated by Django 5.0.1 on 2026-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_shopitem_playercoins_playerpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('player', 'Player'), ('admin', 'Admin'), ('owner', 'Owner')], default='player', max_length=10),
        ),
    ]
