# Generated by Django 5.0.1 on 2026-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_userprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='equipped_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
