# Generated by Django 5.0.1 on 2026-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_equipped_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='equipped_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
